// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: compliance/device_software_compliance.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DeviceSoftwareCompliance struct {
	CDCertificateID       string                   `protobuf:"bytes,1,opt,name=CDCertificateID,proto3" json:"CDCertificateID,omitempty"`
	ComplianceInformation []*ComplianceInformation `protobuf:"bytes,2,rep,name=complianceInformation,proto3" json:"complianceInformation,omitempty"`
}

func (m *DeviceSoftwareCompliance) Reset()         { *m = DeviceSoftwareCompliance{} }
func (m *DeviceSoftwareCompliance) String() string { return proto.CompactTextString(m) }
func (*DeviceSoftwareCompliance) ProtoMessage()    {}
func (*DeviceSoftwareCompliance) Descriptor() ([]byte, []int) {
	return fileDescriptor_22c66eeddd1d6355, []int{0}
}
func (m *DeviceSoftwareCompliance) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeviceSoftwareCompliance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeviceSoftwareCompliance.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeviceSoftwareCompliance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceSoftwareCompliance.Merge(m, src)
}
func (m *DeviceSoftwareCompliance) XXX_Size() int {
	return m.Size()
}
func (m *DeviceSoftwareCompliance) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceSoftwareCompliance.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceSoftwareCompliance proto.InternalMessageInfo

func (m *DeviceSoftwareCompliance) GetCDCertificateID() string {
	if m != nil {
		return m.CDCertificateID
	}
	return ""
}

func (m *DeviceSoftwareCompliance) GetComplianceInformation() []*ComplianceInformation {
	if m != nil {
		return m.ComplianceInformation
	}
	return nil
}

func init() {
	proto.RegisterType((*DeviceSoftwareCompliance)(nil), "zigbeealliance.distributedcomplianceledger.compliance.DeviceSoftwareCompliance")
}

func init() {
	proto.RegisterFile("compliance/device_software_compliance.proto", fileDescriptor_22c66eeddd1d6355)
}

var fileDescriptor_22c66eeddd1d6355 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4e, 0xce, 0xcf, 0x2d,
	0xc8, 0xc9, 0x4c, 0xcc, 0x4b, 0x4e, 0xd5, 0x4f, 0x49, 0x2d, 0xcb, 0x4c, 0x4e, 0x8d, 0x2f, 0xce,
	0x4f, 0x2b, 0x29, 0x4f, 0x2c, 0x4a, 0x8d, 0x47, 0x48, 0xe9, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b,
	0x99, 0x56, 0x65, 0xa6, 0x27, 0xa5, 0xa6, 0x26, 0xe6, 0x40, 0x45, 0x53, 0x32, 0x8b, 0x4b, 0x8a,
	0x32, 0x93, 0x4a, 0x4b, 0x52, 0x53, 0x10, 0x6a, 0x73, 0x52, 0x53, 0xd2, 0x53, 0x8b, 0xf4, 0x10,
	0x02, 0x52, 0xea, 0x48, 0x76, 0x20, 0x98, 0xf1, 0x99, 0x79, 0x69, 0xf9, 0x45, 0xb9, 0x89, 0x25,
	0x99, 0xf9, 0x79, 0x10, 0xf3, 0x95, 0x4e, 0x32, 0x72, 0x49, 0xb8, 0x80, 0x1d, 0x11, 0x0c, 0x75,
	0x83, 0x33, 0x5c, 0xb9, 0x90, 0x06, 0x17, 0xbf, 0xb3, 0x8b, 0x73, 0x6a, 0x51, 0x49, 0x66, 0x5a,
	0x66, 0x72, 0x62, 0x49, 0xaa, 0xa7, 0x8b, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0xba, 0xb0,
	0x50, 0x13, 0x23, 0x97, 0x28, 0xc2, 0x1e, 0x4f, 0x84, 0x35, 0x12, 0x4c, 0x0a, 0xcc, 0x1a, 0xdc,
	0x46, 0x3e, 0x7a, 0x64, 0xf9, 0x43, 0xcf, 0x19, 0x9b, 0x99, 0x41, 0xd8, 0xad, 0x72, 0x4a, 0x3d,
	0xf1, 0x48, 0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07, 0x8f, 0xe4, 0x18, 0x27, 0x3c, 0x96, 0x63,
	0xb8, 0xf0, 0x58, 0x8e, 0xe1, 0xc6, 0x63, 0x39, 0x86, 0x28, 0xef, 0xf4, 0xcc, 0x92, 0x8c, 0xd2,
	0x24, 0x90, 0xc9, 0xfa, 0x10, 0x87, 0xe8, 0xc2, 0x5c, 0xa2, 0x8f, 0xe4, 0x12, 0x5d, 0x84, 0xb9,
	0xba, 0x10, 0xb7, 0xe8, 0x57, 0x20, 0x05, 0x9f, 0x7e, 0x49, 0x65, 0x41, 0x6a, 0x71, 0x12, 0x1b,
	0x38, 0xe4, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x40, 0x34, 0xf3, 0xc1, 0xc8, 0x01, 0x00,
	0x00,
}

func (m *DeviceSoftwareCompliance) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeviceSoftwareCompliance) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeviceSoftwareCompliance) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ComplianceInformation) > 0 {
		for iNdEx := len(m.ComplianceInformation) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ComplianceInformation[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintDeviceSoftwareCompliance(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.CDCertificateID) > 0 {
		i -= len(m.CDCertificateID)
		copy(dAtA[i:], m.CDCertificateID)
		i = encodeVarintDeviceSoftwareCompliance(dAtA, i, uint64(len(m.CDCertificateID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDeviceSoftwareCompliance(dAtA []byte, offset int, v uint64) int {
	offset -= sovDeviceSoftwareCompliance(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DeviceSoftwareCompliance) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CDCertificateID)
	if l > 0 {
		n += 1 + l + sovDeviceSoftwareCompliance(uint64(l))
	}
	if len(m.ComplianceInformation) > 0 {
		for _, e := range m.ComplianceInformation {
			l = e.Size()
			n += 1 + l + sovDeviceSoftwareCompliance(uint64(l))
		}
	}
	return n
}

func sovDeviceSoftwareCompliance(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDeviceSoftwareCompliance(x uint64) (n int) {
	return sovDeviceSoftwareCompliance(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DeviceSoftwareCompliance) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDeviceSoftwareCompliance
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeviceSoftwareCompliance: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeviceSoftwareCompliance: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CDCertificateID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeviceSoftwareCompliance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDeviceSoftwareCompliance
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDeviceSoftwareCompliance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CDCertificateID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ComplianceInformation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeviceSoftwareCompliance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDeviceSoftwareCompliance
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDeviceSoftwareCompliance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ComplianceInformation = append(m.ComplianceInformation, &ComplianceInformation{})
			if err := m.ComplianceInformation[len(m.ComplianceInformation)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDeviceSoftwareCompliance(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDeviceSoftwareCompliance
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDeviceSoftwareCompliance(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDeviceSoftwareCompliance
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDeviceSoftwareCompliance
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDeviceSoftwareCompliance
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDeviceSoftwareCompliance
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDeviceSoftwareCompliance
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDeviceSoftwareCompliance
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDeviceSoftwareCompliance        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDeviceSoftwareCompliance          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDeviceSoftwareCompliance = fmt.Errorf("proto: unexpected end of group")
)
